### ISSUE TITLE
Bosquejos para las reuniones

### ISSUE THREAD

**Issue by josugeek** [livrasand/Reviw#34]
### Nombre del JWPUB

Bosquejos para las reuniones

### Motivo de eliminación

El JWPUB provoca que la app jw library se cierre automaticamente

**Comment by densisono** [comment]
¡Hola!

**Instalacion**: Rapida y sin errores.
**Ejecución**: Sin errores.
**Funcionalidad**: Rapida, graba perfectamente la informacion agregada.
**Compatibilidad**: iPad Pro 12.9", Sexta Generacion, iPadOS 17.1

**Comment by yuniermv** [comment]
Hermanos ya solucioné 2 problema de los **bosquejos para las reuniones.**
No se instala en Android, pero es que tiene por lo menos 3 problemas.
________

**INFORMACIÓN**

En la tabla ``Document`` tiene una fila demás con valores null no válidos.
![Screenshot_20231031-124404.png](https://github.com/livrasand/Reviw/assets/120569483/538ab1a7-b716-4f74-b3b6-ee0effb2ca95)


En la tabla **Publication** (la ficha) en Root Year tiene scpm en lugar de 2022
![Screenshot_20231031-111711.png](https://github.com/livrasand/Reviw/assets/120569483/8841206c-1d23-44dd-9673-505fedf98d7f)


La tabla **extract** tiene referencias erróneas a Cantemos con Gozo (no lo he revisado pero el Blob no se muestra así es que seguro no tiene la información correcta. Este tercer problema también puede radicar en la tabla **RefPublication** al momento de referirse a la ficha de la publicación referida.
El problema ya fue reportado por privado a @livrado Sandoval.

**Comment by yuniermv** [comment]
> Listo, por favor @josugeek prueba ahora si funciona en Android por favor:
> https://wormhole.app/RrqzY#DwLjK0bdyo6C8zqVrLP4jQ

Si. Se instala. No obstante, sigue existiendo el problema de las referencias.
Si lo deseas @livrasand lo corrijo y te lo envío para que lo revises.

**Comment by josugeek** [comment]
> Listo, por favor.@josugeekprueba ahora si funciona en Android por favor: https://wormhole.app/RrqzY#DwLjK0bdyo6C8zqVrLP4jQ

**Comment by josugeek** [comment]
Si ahí funciona, en Android esta ok
