### ISSUE TITLE
Cumple completamente tu ministerio 

### ISSUE THREAD

**Issue by Stephanieoh10** [livrasand/Reviw#66]
### Tipo de problema

Mejora

### Descripción

https://www.jw.org/finder?srcid=jwlshare&wtlocale=S&prefer=lang&pub=pt14

**Comment by livrasand** [comment]
Hola @Stephanieoh10, la publicación pt14 lamentablemente no podemos modificarla, porque se trata de una publicación confidencial limitada a Precursores regulares. No es una publicación publica que podamos compartir con todos.

**Comment by Stephanieoh10** [comment]
Okey hermano. Comprendido!
