### ISSUE TITLE
CO-cdrn24_F no abre

### ISSUE THREAD

**Issue by MisaelArciniega** [livrasand/Reviw#77]
### Nombre del JWPUB

Notes de l’assemblée régionale 2024

### Recursos oficiales

https://github.com/livrasand/Reviw/tree/0455e96ff063141e0eb44005cb28ff5fc54bf256/examples-wts/3-F_Fran%C3%A7ais/CO-cdrn24_F

**Comment by MisaelArciniega** [comment]
No abre con la versión 15.0 de JW Library

**Comment by livrasand** [comment]
@DeadalusNF

**Comment by DeadalusNF** [comment]
Ciao cari, ho inserito 5 giorni fa i nuovi file html. (venerdì-sabato-domenica) e sono in attesa che livrando ricrea i file BLOB corretti.
Puoi inserirli?
Grazie

**Comment by DeadalusNF** [comment]
File corretti in attesa di BLOB
Ti ho inserito i file corretti per aggiornamento BLOB puoi verificare?
Ciao
Fabrizio

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

________________________________
Da: Livrädo Sandoval ***@***.***>
Inviato: Monday, June 24, 2024 4:41:20 PM
A: livrasand/Reviw ***@***.***>
Cc: Fabrizio ***@***.***>; Mention ***@***.***>
Oggetto: Re: [livrasand/Reviw] CO-cdrn24_F no abre (Issue #77)


@DeadalusNF<https://github.com/DeadalusNF>

**Comment by livrasand** [comment]
Mañana los cargo @DeadalusNF, lamentablemente estuve fuera de casa todo el fin de semana. Y hoy trabajé todo el día. Estoy pensando en crear un Action que pueda automatizar el proceso de crear HTML a BLOB, ¿qué opinas?

**Comment by DeadalusNF** [comment]
Eccellente !! Come posso aiutarti?

**Comment by livrasand** [comment]
Hola @DeadalusNF , estoy haciendo los BLOB, no veo los HTML: venerdì-sabato-domenica. ¿donde los has cargado?

**Comment by DeadalusNF** [comment]
Inserito CO-cdrn24_F.jwpub.
Grazie Livrasand.
