### ISSUE TITLE
 Sintaxis "crear" no funciona

### ISSUE THREAD

**Issue by gokusander** [livrasand/Reviw#93]
### Tipo de problema

Otro

### Descripción

A sintaxis "crear" no funciona
Exemplo:
![image](https://github.com/user-attachments/assets/7f9f9c5d-79e4-40e5-bc8a-6f3521eefb63)

Video:
https://github.com/user-attachments/assets/ae9cb5c6-bbe3-44c4-aa79-58274aed92d0

**Comment by livrasand** [comment]
Hola! Las sintaxis quedaron desfasadas a partir de la versión 1.2.x. Para ver la nueva forma de obtener diseños y más fácil, vea las nuevas entradas de la wiki: https://github.com/livrasand/Reviw/wiki/Manual-de-estilo

**Comment by gokusander** [comment]
Gracias, usaré el nuevo formulario.

¿Podrías decirme cómo insertar estas etiquetas en la parte superior?
![image](https://github.com/user-attachments/assets/ece21259-c054-436c-852f-69e07e8c4cad)
Tengo un proyecto nuevo y personal y sería de gran utilidad.

**Comment by gokusander** [comment]
Quiero crear un jwpub con todos los discursos de adoración matutinos transcritos.  ¿Podrías dar algún modelo?

**Comment by livrasand** [comment]
La configuración es esta... 

i. La tabla PublicationViewItem:
![Captura de pantalla (460)](https://github.com/user-attachments/assets/b370d6ce-1d99-4017-a808-20d32a207286)

Debes tener `-1`. Las demás tablas encargadas de la visualización de los items debe ser normal.

**Comment by gokusander** [comment]
Es muy difícil crear un jwpub desde cero. Lo estoy leyendo y releyendo paso a paso, espero poder hacerlo. Ahora encontré JWTOKEN, ¿tienes un link para convertir?

![image](https://github.com/user-attachments/assets/93240867-e263-45c6-9c12-a54a01186f4b)

**Comment by gokusander** [comment]
> La configuración es esta...
> 
> i. La tabla PublicationViewItem: ![Captura de pantalla (460)](https://private-user-images.githubusercontent.com/104039397/363529861-b370d6ce-1d99-4017-a808-20d32a207286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzc4MDIsIm5iZiI6MTczMTAzNzUwMiwicGF0aCI6Ii8xMDQwMzkzOTcvMzYzNTI5ODYxLWIzNzBkNmNlLTFkOTktNDAxNy1hODA4LTIwZDMyYTIwNzI4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwMzQ1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2I4NzFmNTliM2JmYjNlYjQyZmQwM2NlNjY3YzFkMTdhMjIyMGU4NTBmZGMyMTllZTFlODA4YmZjZDFkZTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eOHzvJpyqps4s90Ffv-irnRMtpEkObpyeE0RxkjRdc0)
> 
> Debes tener `-1`. Las demás tablas encargadas de la visualización de los items debe ser normal.

¿Podrías explicar detalladamente cómo funciona? Me gustaría separar por pestañas y títulos.

![image](https://github.com/user-attachments/assets/c66e54c8-40b8-453e-8237-7d1d9e4e2286)
