### ISSUE TITLE
Tradução SCPm para portugues

### ISSUE THREAD

**Issue by Igorjesus96** [livrasand/Reviw#96]
### Nombre del JWPUB

Guia de presidência das Reuniões

### Repositorio

https://github.com/Igorjesus96/scpm_T.git

### MepsLanguage

5

### Año

2024

### Symbol

scpm_T

### Recursos oficiales

![programs-events_univ_pnr_lg](https://github.com/user-attachments/assets/cf82fc1a-e70d-4be2-915e-a39a8782589a)
![scpm_univ_sqr120x120](https://github.com/user-attachments/assets/c8e52295-046c-4a4f-b206-2361a8681632)
![scpm_univ_sqr270x270](https://github.com/user-attachments/assets/7d8c7628-cf10-4c68-bc5d-38269b0619bf)
![scpm_univ_sqr600x600](https://github.com/user-attachments/assets/b83fb5ab-388d-429f-b69d-aa68321f9f99)
![scpm_univ_sqs_lg](https://github.com/user-attachments/assets/afe646b5-c2d6-4360-a2b4-8c3ce0797cf5)
![scpm_univ_sqs_mem](https://github.com/user-attachments/assets/b07cd475-5d04-4577-bb00-4f0bb92eafff)

### Comentarios adicionales

DESEJO TRADUZIR ESSE Jwpub para português

**Comment by livrasand** [comment]
Hola, muchas gracias por tu buen deseo. Tienes los archivos traducidos? O solicitas la traducción de nuestra parte?

**Comment by Igorjesus96** [comment]
Hola hermano, ya traduje los archivos, quería saber el siguiente paso. Creo que está generando el blob para insertarlo en la base de datos.

**Comment by Igorjesus96** [comment]
Hola hermano, traduce los archivos, quisiera saber el siguiente paso. Creo que está generando el blob para insertarlo en la base de datos. 

 En mi repositorio, el manifiesto y los html ya están traducidos a PT.

**Comment by livrasand** [comment]
Muy bien 🎉 para solicitar los BLOBs, debes seguir este proceso: 

https://github.com/livrasand/Reviw/wiki/Solicitar-los-BLOB-para-los-HTML

**Comment by livrasand** [comment]
Atendido en #97
