### ISSUE TITLE
Guia de Presidencia das Reunioes scpm_T

### ISSUE THREAD

**Issue by Igorjesus96** [livrasand/Reviw#97]
### Nombre del JWPUB

Guia de Presidencia das Reuniões

### Repositorio

https://github.com/Igorjesus96/scpm_T.git

### MepsLanguage

5

### Año

2024

### Symbol

scpm_T

### Recursos oficiales

[htmls.zip](https://github.com/user-attachments/files/17021418/htmls.zip)

### Comentarios adicionales

Hola hermano, estoy enviando los htmls para generar los blobs. Podría comprobar si hay algo mal con el json y el *.db ? He intentado seguir tu tutorial al pie de la letra, espero no haber fallado. Es sólo una traducción, no es una nueva publicación.

**Comment by MisaelArciniega** [comment]
Hola, te dejo mi revisión de tus archivos en 3 partes.

**Manifest**
1. timestamp": "2024-09-14T23:47:34-03:00", le falta una Z en ambos timestamp en el manifest, debe ser "2024-09-14T23:47:34-03:00Z" 
2. "rootLanguage": 0 en el manifest, 1 en la tabla Publication. Este dato debe concordar. En ambos debe ser 1 en este caso. 
3. "displayTitle": "Guia de presidência das Reuniões  (scpm)", le falta un espacio entre "Reuniões" y (scpm), deben ser dos espacios
4. "language": 5 en el manisfest; MepsLanguageIndex: 1 en la tabla Publication. Este dato debe concordar. En ambos debe ser 5.
5. "symbol": "scpm", debe ser scpm_T en el manifest y la tabla Publication 
6. "uniqueEnglishSymbol": "scpm", debe ser scpm_T en el manifest y la tabla Publication 
7. "uniqueSymbol ": "scpm", debe ser scpm_T en el manifest y la tabla Publication 
8. "undatedSymbol": "scpm", debe ser scpm_T en el manifest y la tabla Publication 
9. "englishSymbol": "scpm", debe ser scpm_T en el manifest y la tabla Publication 

Lo de los symbol es así porque así lo solicitaste:
![Screenshot_20240916_215347_com brave browser](https://github.com/user-attachments/assets/0a30bb46-0744-48ec-b804-922738f01dd2)

Este dato solo debe pedirse así:
Ejemplo: scpm. 
Este _T es la extensión de idioma
Quizá te confundió que así aparece en la solicitud de jwpub, pero ténlo en cuenta para las próximas ocasiones. 
![Screenshot_20240916_211102_com brave browser](https://github.com/user-attachments/assets/83cfda1a-8895-485f-931a-ded7d4fa490c)


Este bloque va vacío, solo La Atalaya usa este bloque.
"issueProperties": { 
				"title": "Guia de presidência das Reuniões",
				"undatedTitle": "Guia de presidência das Reuniões",
				"coverTitle": "Guia de presidência das Reuniões",
				"titleRich": "Guia de presidência das Reuniões",
				"undatedTitleRich": "Guia de presidência das Reuniões",
				"coverTitleRich": "Guia de presidência das Reuniões",
				"symbol": "scpm_T",
				"undatedSymbol": ""
		}


**Base de datos**
1. La columna Title y TocTitle en la tabla Document deben concordar. Solo copia los datos de las 3 columna TocTitle y pegalos en las columnas Title
2. Las tres columnas MepsLanguageId en la tabla Multimedia la puedes dejar en null

**Archivos htm**
En tu archivo Reunião Pública.htm puedes cambiar el enlace del párrafo 23 <code><a class="xt" data-xtid="2" href="jwpub://p/T:202007165/"><em>km 5/07 pág. 3</em></a></code> por <code><a href="jwpub://p/T:202007165/"><em>km 5/07 pág. 3</em></a></code>, te dará una descarga automática dentro de JW Library. 
Luego borras las columnas de la tabla Extract y RefPublication. 
También evita dejar los 3 scripts iniciales.

**Comment by livrasand** [comment]
Ya están listos tus BLOB

https://github.com/livrasand/Reviw/tree/e2e71890801d5486b4fdbe38cfbd93659725082b/examples-wts/5-T_portugu%C3%AAs/scpm_T/contents~/htmls/blobs
