### ISSUE TITLE
JW Library api in Codepen

### ISSUE THREAD

**Issue by gokusander** [livrasand/Reviw#98]
### Tipo de problema

Otro

### Descripción

Buenas noches, anteriormente había puesto a disposición una API en el sitio web de Codepen donde podíamos comprobar cómo se vería el htm. El enlace ha sido eliminado, ¿sería posible volver a ponerlo a disposición?

Enlace antiguo: https://github.com/livrasand/Reviw/tree/main/docs

**Comment by livrasand** [comment]
Hola! Si claro que sí, de hecho se mejoró hace poco, falta la actualización! En unas horas lo actualizaré 👍🏻

**Comment by livrasand** [comment]
https://codepen.io/livrasand/full/rNPBqOM

Listo mi hermano, muchas gracias por la observación.

**Comment by gokusander** [comment]
> https://codepen.io/livrasand/full/rNPBqOM
> 
> Listo mi hermano, muchas gracias por la observación.

Not working anymore?
